version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: best_travel_db
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=best_travel
      - POSTGRES_USER=hegaro
      - POSTGRES_PASSWORD=4m4t1st4*
    ports:
      - "5433:5432"
    networks:
      - best_travel_default

  cache-db:
    image: redis:6.2-alpine
    container_name: best_travel_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass debuggeandoideas
    networks:
      - best_travel_default

  document-db:
    image: mongo:6.0.4
    restart: always
    container_name: best_travel_users
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: debuggeandoideas
      MONGO_INITDB_DATABASE: users
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - best_travel_default

networks:
  best_travel_default:
    name: best_travel_default
    driver: bridge